INSERT INTO `MyHealth_DB`.`questions`
(
`question`,
`category_id`)
VALUES
('Does your kid lift head when lying on stomach ? ( you can let your kid lie on his stomach and communicate from the front and see if raises head to listen to you or to see you)','1'),
('Is your kid able to carry very light wooden blocks on head and walk 5 steps ?','1'),
('Is your kid able to crawl ? ','1'),
('Is your kid able to get himself up from a squatting position without any help ?','1'),
('Is your kid able to hop on one foot ? ( able to jump or take a step on one foot )','1'),
('Is your kid able to sit alone ? ( without any support/help)','1'),
('Is your kid able to stand alone ? ( can help/support to let stand and then leave him/her in standing position)','1'),
('Is your kid able to stand on one foot with help/support? ','1'),
('Is your kid able to walk backwards ? ','1'),
('When you pull your kid to a sitting position, Does his/her head lag much ? ( i.e. Your kid is able to hold his head in position for sometime atleast)','1'),
(' Does your kid attempts to imitate of your scribble ? ( scribble with crayon on a paper in front of your kid and see if your kid tries to do the same)','2'),
('Does your kid grasp objects ? ( i.e. your kid is able to put a little hold onto an object for eg a plastic square block )','2'),
('Does your kid makes ball from dough or clay ?','2'),
('Does your kid pick up cubes/pebbles ? ( you can spread pebbles or plastic cubes on the floor and see if your kid picks them up)','2'),
('Does your kid reach for objects ? ( i.e. if you show your kid a toy or similar object, your kid tries to reach it to grab/hold it)','2'),
('Does your kid snap thumb and fingers ? (You can snap your thumb and finger to show how to snap and make sound )','2'),
('For pebbles/cubes lying around, does your kid put 3-4 of them in a cup if provided ? ( provide a cup or bucket or basket with pebbles or plastic cubes lying on floor)','2'),
('If you draw a circle, is your kid able to draw a circle in imitation ?','2'),
('If you draw a diamond, is your kid able to draw a diamond in imitation ?','2'),
('If you draw a square, is your kid able to draw a square in imitation ?','2'),
('If you draw a straight line, is your kid able to draw a straight line in imitation ?  ( you can draw on a paper/slate and give your kid a pencil/chalk with paper/slate at the same time)','2'),
('Is your child able to sustain attention to one structured activity for 2-3 minutes ?','2'),
('Is your kid able to close one eye lid ?','2'),
('Is your kid able to move thumb ? ','2'),
('Is your kid able to thread one bead with nylon wire ?','2'),
('When you move an object  in front of your kids face, does she follow the moving object momentarily ? ( i.e. you move a toy or similar and your kids eyes follow the object)','2'),
('Does your kid respond to sounds ?','3'),
('Does your kid complete a sentence ?','3'),
('Does your kid enjoy looking at pictures ?','3'),
('Does your kid identifies one object ?','3'),
('Does your kid manipulate bell ? ','3'),
('Does your kid name any one object ?','3'),
('Does your kid names three objects ?','3'),
('Does your kid points to four parts of body ?','3'),
('Does your kid points to two parts of body ?','3'),
('Does your kid recognizes three colours ?','3'),
('Does your kid relates to objects ?','3'),
('Does your kid repeat a word or number ?','3'),
('Does your kid repeat two numbers ?','3'),
('Does your kid ring the bell ?','3'),
('Does your kid say any one word ?','3'),
('Does your kid speak two words together ?','3'),
('Does your kid two lines of songs/folklore ?','3'),
('Does your kid understand concept of big and little ?','3'),
('Does your kid understand concept of heavy and light ?','3'),
('Does your kid understand money ?','3'),
('Does your kid understand prepositions ?','3'),
('Does your kid feed self in any way ?','4'),
('Does your kid cleans teeth ?','4'),
('Does your kid control bladder during day ?','4'),
('Does your kid control bladder during night ?','4'),
('Does your kid control bowel during day ?','4'),
('Does your kid control bowel during night ?','4'),
('Does your kid dresses up without help ?','4'),
('Does your kid drink from cup or glass ?','4'),
('Does your kid feeds self appropriately ?','4'),
('Does your kid visit key places in villages ?','4'),
('Does your kid washes face ?','4'),
('Does your kid washes hand ?','4'),
('Does your kid smiles in response ?','5'),
('Does your kid has awareness of strangers ?','5'),
('Does your kid identify gender ?','5'),
('Does your kid play with other children ?','5'),
('Does your kid tell his/her name ?','5'),
('Does your kid understand the rules of a game ?','5'),
('Does your kid vocalizes in response ?','5')

;
